<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>algo</string>
		<string>alg</string>
	</array>
	<key>name</key>
	<string>Pseudocode (HEIG-VD)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:const|vaut|c\`est|si|sinon|alors|fin_si|var|fonction|fin_fonction|retourner|repeter|jusqu\`a)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:et|ou|non|ou_exclusif|mod)\b</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Inline comments</string>
			<key>match</key>
			<string>(\/\/.*)</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Za-z0-9_]+)\(</string>
			<key>name</key>
			<string>meta.function</string>
			<key>patterns</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:vrai|faux)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\".*\")</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:entier|reel|caractere|chaine|booleen)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Z][A-Z0-9_]*)\b</string>
			<key>name</key>
			<string>constant.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9_]+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Za-z][A-Za-z0-9_]+)\b</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pseudocode</string>
	<key>uuid</key>
	<string>fd7cdfbf-a6be-4e7e-8db5-b28e46055c52</string>
</dict>
</plist>
